### PR TITLE
Create nko.ts

### PR DESCRIPTION
**Pull request by kjitteh**
## Description

Simple keyboard layout for N'ko script with all Unicode character included, layout follows Qwerty keyboard layout.
<https://unicode-table.com/en/blocks/nko/>
## Checks

- [x] Tests ( `npm run test` ) are passing

### CODE REVIEW

**Comment by hodgef** [comment]
Sorry for the delay, will follow up & merge this PR shortly. Thanks!

**Comment by kjitteh** [comment]
thanks, looking forward to using it in projects soon

**Comment by hodgef** [comment]
Thanks for the contribution @kjitteh! The N'ko layout is now live as of the latest version. Feel free to update and check it out.

Regards,
Francisco Hodge

**Comment by kjitteh** [comment]
glad to have contributed

**Pull request merged**
